adds header html
IhorKulinskyi/ice-cream pull request #19
Opened 2022-10-08 15:18 UTC by Vasiliy8P

2022-10-08 17:07 UTC, IhorKulinskyi requested changes
у тебе одна й та ж сама розмітка повторюєтся два рази, це зайве.Потім за допомогою медіаправил у стилях можна змінити значення для кожного елемента .

2022-10-08 17:18 UTC, Vasiliy8P commented
Поясню, це дві різні розмітки, одна для хедера, друга для планшетного/мобільного меню (в них приблизно однаковий список навігації), але працювати мають по різному

2022-10-09 08:36 UTC, IhorKulinskyi commented on src/partials/header.html
> +    <div class="conteiner">
синтаксична помилка у імені классу

2022-10-09 08:39 UTC, IhorKulinskyi requested changes
1.Прибери поки що папку з зображеннями,додаш їх у вже існуючу папку img
2.Виправ назву классу container
Загалом чудово!

2022-10-09 08:44 UTC, Vasiliy8P commented
Все виправи, дякую

2022-10-09 08:46 UTC, IhorKulinskyi approved these changes

2022-10-09 08:47 UTC, merged