About geometry
IhorKulinskyi/ice-cream pull request #25
Opened 2022-10-08 19:35 UTC by march1ck

зробив спочатку без картинки, бо стягнув до того як ти запушив,  є тільки геометрія

2022-10-08 20:10 UTC, march1ck commented
у розмітці добавив один дів з класом

2022-10-09 08:53 UTC, IhorKulinskyi commented on src/sass/components/_about.scss
> +  margin-bottom: 54px;
в мобілці ти рахуеш марджин без тіні, в планшеті з тінню , зроби щоб будло однаково

2022-10-09 08:56 UTC, IhorKulinskyi commented on src/sass/components/_about.scss
> +  .about__box-content {
я бачу 100 на макеті, а не 108

2022-10-09 08:59 UTC, IhorKulinskyi requested changes
Дуже добре, але є два маленьких нюанси

1.Визначись як ти рахуешь марджин заголовка секції,з тінню чи без та перевір щоб навсіх пристроях це було однаково.
2.Переглянь макет десктопної версії та поправ gap для .about-box-content

2022-10-09 14:50 UTC, march1ck commented
запушив

2022-10-09 14:51 UTC, march1ck commented
там конфлікт в утилітах

2022-10-09 14:53 UTC, IhorKulinskyi requested changes
зроби фетч та пулл , потім запуш ще раз,подивимося чи зникне

2022-10-09 14:54 UTC, march1ck commented
в цій же гілці?

2022-10-09 14:54 UTC, IhorKulinskyi commented
так

2022-10-09 15:06 UTC, IhorKulinskyi commented
https://frontend-stuff.com/blog/updating-git-branch/

надо сначала обновить свой мейн, сорян, и тогда можешь картинку уже добавить

2022-10-09 15:16 UTC, march1ck commented
наче вирішив

2022-10-09 15:56 UTC, IhorKulinskyi commented
подивись яка структура в мейні у головному репозиторії і яка в тебе, в тебе немає папки з зображеннями, значить зміни не стянулись

2022-10-09 15:57 UTC, IhorKulinskyi commented
і конфлікт як був так і є

2022-10-09 16:26 UTC, march1ck commented
тепер?

2022-10-09 16:32 UTC, IhorKulinskyi commented
тепер є,можеш додати збраження та сдати геометрію вже з ним,бобез нього не цікавво)

2022-10-09 16:34 UTC, march1ck commented
погоджуюсь, а що це було? я так і не зрозумів

2022-10-10 08:44 UTC, IhorKulinskyi approved these changes

2022-10-10 08:44 UTC, merged

2022-10-10 16:21 UTC, march1ck commented
ти пофіксив, там де я клас не замінив на img?