make footer-tel geometry
IhorKulinskyi/ice-cream pull request #26
Opened 2022-10-08 22:43 UTC by Aleksey100ckiy

Доброго часу доби) глянь, будь ласка. Я повісив мардин топ на ul, бо коли вішав а попердній заголовок, то чамвсь марджин провалювався та не відштовхував елемент. Завтра продовжу на табл і десктоп. Планую допиляти ще по плейсхолдерам на флекси

2022-10-09 09:07 UTC, IhorKulinskyi commented on src/sass/components/_footer.scss
> +    padding-top: 38px;
краще додай цей паддінг на футер , а е на тайтл

2022-10-09 09:09 UTC, IhorKulinskyi commented on src/sass/components/_footer.scss
> +    margin-bottom: 40px;
пpопиши марджин 40 не для tel-info, а для footer-contacts

2022-10-09 09:12 UTC, IhorKulinskyi requested changes
Дуже добре!
Правки написав у коментах до коду.
Також ми домовились писати одразу з медіазапитами під усі пристрої, так що разом із правками можеш зробити геометрію для планшета та десктопа.

Гарна робота!

2022-10-09 12:02 UTC, Aleksey100ckiy commented on src/sass/components/_footer.scss
> +    margin-bottom: 40px;
дякую, сідаю за роботу)

2022-10-10 08:41 UTC, IhorKulinskyi approved these changes
добре,я заливаю, марджин ще допрацюєш

2022-10-10 08:41 UTC, merged