add styles to section about
IhorKulinskyi/ice-cream pull request #45
Opened 2022-10-10 23:15 UTC by march1ck

2022-10-10 23:16 UTC, march1ck commented
щодо картинки, то її робити з тінню чи витягувати абсолютом,як у тз прописано?

2022-10-11 10:44 UTC, IhorKulinskyi requested changes
Чудова робта!
залшилосязробити зображення бекграундом і все буде готово

2022-10-11 13:38 UTC, march1ck commented
і конфлікт вирішити

2022-10-11 14:03 UTC, IhorKulinskyi requested changes
1.Додай паддінг топ на секцію
2.Вже можна прибрати сursor та transition з кнопоки,все це є у плейсхолдері
3.Зробити корову як бекграунд та додати тінь

2022-10-11 19:17 UTC, march1ck commented
+знову конфлікт

2022-10-11 21:52 UTC, IhorKulinskyi approved these changes
Поки що апрувлю,щоб паддінги вже зрбити,потім ще з тінню треба погратися,щоб була як на макеті

2022-10-11 21:52 UTC, merged